LOCAL_SRC_FILES += \
				   ../../Classes/protobuf2.5/google/protobuf/io/coded_stream.cc                \
				   ../../Classes/protobuf2.5/google/protobuf/extension_set_heavy.cc            \
				   ../../Classes/protobuf2.5/google/protobuf/stubs/common.cc                   \
				   ../../Classes/protobuf2.5/google/protobuf/descriptor.cc                     \
				   ../../Classes/protobuf2.5/google/protobuf/descriptor.pb.cc                  \
				   ../../Classes/protobuf2.5/google/protobuf/descriptor_database.cc            \
				   ../../Classes/protobuf2.5/google/protobuf/dynamic_message.cc                \
				   ../../Classes/protobuf2.5/google/protobuf/extension_set.cc                  \
				   ../../Classes/protobuf2.5/google/protobuf/generated_message_reflection.cc   \
				   ../../Classes/protobuf2.5/google/protobuf/generated_message_util.cc         \
				   ../../Classes/protobuf2.5/google/protobuf/io/gzip_stream.cc                 \
				   ../../Classes/protobuf2.5/google/protobuf/compiler/importer.cc              \
				   ../../Classes/protobuf2.5/google/protobuf/message.cc                        \
				   ../../Classes/protobuf2.5/google/protobuf/message_lite.cc                   \
				   ../../Classes/protobuf2.5/google/protobuf/stubs/once.cc                     \
				   ../../Classes/protobuf2.5/google/protobuf/compiler/parser.cc                \
				   ../../Classes/protobuf2.5/google/protobuf/io/printer.cc                     \
				   ../../Classes/protobuf2.5/google/protobuf/reflection_ops.cc                 \
				   ../../Classes/protobuf2.5/google/protobuf/repeated_field.cc                 \
				   ../../Classes/protobuf2.5/google/protobuf/service.cc                        \
				   ../../Classes/protobuf2.5/google/protobuf/stubs/structurally_valid.cc       \
				   ../../Classes/protobuf2.5/google/protobuf/stubs/strutil.cc                  \
				   ../../Classes/protobuf2.5/google/protobuf/stubs/substitute.cc               \
				   ../../Classes/protobuf2.5/google/protobuf/text_format.cc                    \
				   ../../Classes/protobuf2.5/google/protobuf/io/tokenizer.cc                   \
				   ../../Classes/protobuf2.5/google/protobuf/unknown_field_set.cc              \
				   ../../Classes/protobuf2.5/google/protobuf/wire_format.cc                    \
				   ../../Classes/protobuf2.5/google/protobuf/wire_format_lite.cc               \
				   ../../Classes/protobuf2.5/google/protobuf/io/zero_copy_stream.cc            \
				   ../../Classes/protobuf2.5/google/protobuf/io/zero_copy_stream_impl.cc       \
				   ../../Classes/protobuf2.5/google/protobuf/io/zero_copy_stream_impl_lite.cc  \
				   ../../Classes/protobuf2.5/google/protobuf/stubs/stringprintf.cc
